runtime: nodejs18
env: standard

runtime_config:
  operating_system: 'ubuntu22'

handlers:
  # Serve all static files from the 'dist' directory
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$

  # Redirect all other URLs to 'index.html' to handle client-side routing
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
