# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a release is created

name: 'Build and Deploy PROD to  Cloud Run'

on:
    pull_request:
      branches:
        - release
      types:
        - closed

env:

  PROJECT_ID: ${{ env.PROJECT_ID }}
  REGION: ${{ secrets.REGION_LOC_1 }}
  SERVICE: 'vmt'
  IMAGE_NAME: 'vmt_img'
  GCP_CREDENTIALS:  ${{ secrets.GCP_CREDENTIALS }}


jobs:
  
  deploy:
    runs-on: 'ubuntu-latest'

    
    environment:
      name: prod

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: 'Print Environment Variables'
        run: |
          echo "PROJECT_ID: ${{ env.PROJECT_ID }}"
          echo "SERVICE: ${{ env.SERVICE }}"
           # ... print other relevant variables
     
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build Docker Image' # New step to build the image
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t "${DOCKER_TAG}" .

      - name: 'Push Docker Image'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"