name: Deploy to Cloud Run

on:
  push:
    branches:
      - gitub-deploy  # Adjust if you use a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: dev

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud using a Service Account
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Ensure this secret is correctly set in GitHub Secrets

      # Step 3: Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Ensure this secret is also set

      # Step 4: Build and push Docker image to Google Container Registry (GCR)
      - name: Build and push Docker image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/VMT_dev:$GITHUB_SHA
          docker build -t $IMAGE .
          docker push $IMAGE

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/VMT_dev:$GITHUB_SHA
          gcloud run deploy github-actions-deploy \
            --image $IMAGE \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated
