# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a  when a release is created.

name: 'Build and Deploy QA to Cloud Run'

on:
  push:
    branches:
      - github-deploy  # Adjust if you use a different branchc


env:

  PROJECT_ID: map-dragon-uat
  REGION: ${{ secrets.REGION_LOC_1 }}
  SERVICE: 'mapDragon_qa'
  IMAGE_NAME: 'mapDragon_qa_img'
  GCP_CREDENTIALS:  ${{ secrets.GCP_CREDENTIALS }}


jobs:
  
  deploy:
    runs-on: 'ubuntu-latest'

    
    environment:
      name: qa

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Print Environment Variables'
        run: |
          echo "PROJECT_ID: ${{ env.PROJECT_ID }}"
          echo "SERVICE: ${{ env.SERVICE }}"
          # ... print other relevant variables
     
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'

      - name: Generate .env.dev file
        run: |
          echo "VITE_CLIENT_ID = ${{ secrets.VITE_CLIENT_ID }}" > .env.dev
          echo "VITE_SEARCH_ENDPOINT = ${{ secrets.VITE_SEARCH_ENDPOINT }}" >> .env.dev
          echo "VITE_VOCAB_ENDPOINT= ${{ secrets.VITE_VOCAB_ENDPOINT }}" >> .env.dev

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build Docker Image' # New step to build the image
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t "${DOCKER_TAG}" --build-arg ENV=qa .

      - name: 'Push Docker Image'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"