name: Deploy to Cloud Run

on:
  push:
    branches:
      - github-deploy  # Adjust if you use a different branchc

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: dev

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Ensure this secret is correctly set in GitHub Secrets

    
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Ensure this secret is also set

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker '${{ env.REGION }} --docker.pkg.dev' 

      - name: Build and push Docker image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/vmt:$GITHUB_SHA
          docker build -t $IMAGE .
          docker push $IMAGE

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/vmt:$GITHUB_SHA
          gcloud run deploy vmt \
            --image $IMAGE \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated
